name: 'Nostr Action'
description: 'Send events with nostr'
inputs:
  key:
    description: 'nostr private key'
    required: true
  relay:
    description: 'nostr relay'
    required: true
    default: 'wss://nostr-pub.wellorder.net'
  content:
    description: 'nostr content'
    required: true
  dry:
    description: dry-run mode - connection to relays will be established, but no event will be sent
    type: boolean
    default: false
    
outputs:
  event:
    description: 'The published event as JSON string'
runs:
  using: 'node20'
  main: 'dist/index.js'
