name: Send Nostr Event

on:
  workflow_dispatch:
    inputs:
      key:
        description: private key (e.g. 0123456789abcdef...)
        required: true
      relay:
        description: relay (e.g. wss://relay.damus.io)
        type: choice
        options: 
        - wss://nostr-pub.wellorder.net
        - wss://relay.damus.io
        - wss://relay.primal.net
        - wss://nostr.swiss-enigma.ch
        - wss://nostr.rocks
        - wss://relay.nostr.band
        - wss://nostr.bitcoiner.social
      content:
        description: content (e.g. hello world!)
        required: true
      dry:
        description: dry-run mode - connection to relays will be established, but no event will be sent
        type: boolean
        default: false
        required: true

jobs:
  units:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Publish event via nostr
        uses: theborakompanioni/nostr-action@v1
        with:
          dry: ${{ github.event.inputs.dry }}
          key: ${{ github.event.inputs.key }}
          relay: ${{ github.event.inputs.relay }}
          content: ${{ github.event.inputs.content }}
